data_dir: data
results_dir: wav # output example ./data/IEMOCAP_mcadams/wav

pipeline: mcadams
anon_suffix: !ref _<pipeline>

datasets:
  - name: libri_dev_clean
    data: libri_dev_clean
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: libri_test_clean
    data: libri_test_clean
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: train-clean-360
    data: train-clean-360

modules:
  anon_suffix: !ref <anon_suffix>
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  # anon_level_spk: [IEMOCAP_test, IEMOCAP_dev, libri_dev_clean, libri_test_clean]
  anon_level_utt: [train-clean-360, libri_dev_clean, libri_test_clean]
