data_dir: data
results_dir: wav # output example ./data/IEMOCAP_mcadams/wav

pipeline: mcadams
anon_suffix: !ref _<pipeline>

datasets:
  - name: IEMOCAP_dev
    data: IEMOCAP_dev
  - name: IEMOCAP_test
    data: IEMOCAP_test
  - name: libri_dev
    data: libri_dev
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: libri_test
    data: libri_test
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: train-clean-360
    data: train-clean-360

modules:
  anon_suffix: !ref <anon_suffix>
  n_coeffs: 20
  mc_coeff_min: 0.5
  mc_coeff_max: 0.9
  winLengthinms: 20
  shiftLengthinms: 10
  seed: 0
  # anon_level_spk: [IEMOCAP_test, IEMOCAP_dev, libri_dev, libri_test]
  anon_level_utt: [train-clean-360, IEMOCAP_test, IEMOCAP_dev, libri_dev, libri_test]